<select class="form-control page_custom_form_control" name="control">
    <option selected="1">Select a Category</option>
    <option value="0">Airport</option>
    <option value="1">Arts/Entertainment/Nightlife</option>
    <option value="2">Attractions/Things to do</option>
    <option value="3">Automotive</option>
    <option value="4">Bank/Financial Services</option>
    <option value="5">Bar</option>
    <option value="6">Book Store</option>
    <option value="7">Business Services</option>
    <option value="8">Church/ Religious Organization</option>
    <option value="9">Club</option>
    <option value="10">Community/ Government</option>
    <option value="11">Concert Venue</option>
    <option value="12">Doctor</option>
    <option value="13">Event Planning/Event Services</option>
    <option value="14">Food/Grocery</option>
    <option value="15">Health/Medical/Pharmacy</option>
    <option value="16">Home Improvement</option>
    <option value="17">Hospital/Clinic</option>
    <option value="18">Hotel</option>
    <option value="19">landmark</option>
    <option value="20">Lawyer</option>
    <option value="21">Library</option>
    <option value="22">Licensed Financial Representative</option>
    <option value="23">Local Business</option>
    <option value="24">Middle School</option>
    <option value="25">Movie Theater</option>
    <option value="26">Museum/Art Gallery</option>
    <option value="">Outdoor Gear/Sporting Goods</option>
    <option value="">Pet Services</option>
    <option value="">Professional Services</option>
    <option value="">Public Places</option>
    <option value="">Real Estate</option>
    <option value="">Restaurant/Cafe</option>
    <option value="">School</option>
    <option value="">Shopping/Retail</option>
    <option value="">Spas/Beauty/Personal Care</option>
    <option value="">Sports Venue</option>
    <option value="">Sports/Recreation/Activities</option>
    <option value="">Tours/Sightseeing</option>
    <option value="">Transportation</option>
    <option value="">University</option>    
</select>